--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/GameParrot/libpmcurl
build-by-default: true
branches:
- main
projects:
  libpmcurl:
    path: ""
    model: virion
    type: library
...
